// 主题切换逻辑
if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.documentElement.classList.add('dark');
} else {
    document.documentElement.classList.remove('dark');
}

function toggleTheme() {
    // 添加过渡动画类
    document.body.classList.add('theme-transition');
    
    if (document.documentElement.classList.contains('dark')) {
        document.documentElement.classList.remove('dark');
        localStorage.theme = 'light';
    } else {
        document.documentElement.classList.add('dark');
        localStorage.theme = 'dark';
    }
    
    // 移除过渡动画类，以便下次切换时重新触发
    setTimeout(() => {
        document.body.classList.remove('theme-transition');
    }, 300);
}

// 语言切换逻辑
let currentLang = localStorage.getItem('lang') || 'zh';

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('lang', lang);
    updateContent();
}

function updateContent() {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[currentLang] && translations[currentLang][key]) {
            element.textContent = translations[currentLang][key];
        }
    });
}

// 翻译数据
const translations = {
    zh: {
        title: 'expo-liteDBStore',
        subtitle: '轻量级本地存储解决方案',
        description: '为 React Native + Expo 项目设计，无需任何 native 依赖。',
        features: '核心特性',
        feature1: '零依赖、零配置',
        feature2: '完整 TypeScript 支持',
        feature3: '支持加密存储',
        feature4: '支持事务操作',
        feature5: '支持复杂查询',
        feature6: '支持分块存储',
        quickstart: '快速开始',
        installation: '安装',
        installationCmd: 'npm install expo-lite-db-store',
        usage: '基本使用',
        api: 'API 文档',
        architecture: '架构设计',
        guides: '使用指南',
        examples: '示例代码',
        contribute: '贡献指南',
        changelog: '更新日志',
        license: '许可证',
        themeToggle: '切换主题',
        langToggle: '切换语言',
        home: '首页',
        gettingStarted: '入门指南',
        reference: 'API 参考',
        community: '社区',
        search: '搜索...',
        light: '浅色',
        dark: '深色',
        system: '系统',
        gettingStartedTitle: '开始使用 expo-liteDBStore',
        gettingStartedSubtitle: '快速上手轻量级本地存储解决方案，为 React Native + Expo 项目设计。',
        prerequisites: '前提条件',
        prereq1: 'React Native 项目',
        prereq2: 'Expo SDK 49+',
        prereq3: 'Node.js 16+',
        installationGuide: '安装指南',
        installationSteps: '安装步骤',
        step1: '步骤 1: 安装依赖',
        step2: '步骤 2: 配置（可选）',
        step3: '步骤 3: 开始使用',
        configuration: '配置',
        configurationFile: '配置文件',
        configurationExample: '配置示例',
        basicUsage: '基本使用',
        createTable: '创建表',
        insertData: '插入数据',
        queryData: '查询数据',
        updateData: '更新数据',
        deleteData: '删除数据',
        nextSteps: '下一步',
        nextStep1: '查看 API 参考',
        nextStep2: '查看示例代码',
        nextStep3: '了解架构设计',
        nextStep4: '加入社区讨论',
        apiTitle: '完整的 API 文档',
        apiSubtitle: '详细了解 expo-liteDBStore 的所有 API 方法和用法。',
        tableOperations: '表操作',
        dataOperations: '数据操作',
        transactions: '事务管理',
        cacheOperations: '缓存操作',
        utilityFunctions: '工具函数',
        deleteTable: 'deleteTable',
        hasTable: 'hasTable',
        listTables: 'listTables',
        countTable: 'countTable',
        clearTable: 'clearTable',
        insert: 'insert',
        read: 'read',
        findOne: 'findOne',
        findMany: 'findMany',
        update: 'update',
        remove: 'remove',
        bulkWrite: 'bulkWrite',
        beginTransaction: 'beginTransaction',
        commit: 'commit',
        rollback: 'rollback',
        migrateToChunked: 'migrateToChunked',
        setCacheSize: 'setCacheSize',
        clearCache: 'clearCache',
        getCacheStats: 'getCacheStats',
        description: '描述',
        parameters: '参数',
        returns: '返回值',
        example: '示例',
        tableName: 'tableName',
        options: 'options',
        data: 'data',
        filter: 'filter',
        where: 'where',
        operations: 'operations',
        encrypted: 'encrypted',
        autoIndex: 'autoIndex',
        indexes: 'indexes',
        skip: 'skip',
        limit: 'limit',
        sort: 'sort',
        boolean: '布尔值',
        string: '字符串',
        number: '数字',
        object: '对象',
        array: '数组',
        promise: 'Promise',
        void: 'void',
        writeResult: 'WriteResult',
        record: 'Record',
        null: 'null',
        true: 'true',
        false: 'false',
        usageExample: '使用示例',
        architectureTitle: '架构设计',
        architectureSubtitle: 'expo-liteDBStore 的架构设计和核心组件',
        layeredArchitecture: '分层架构',
        apiLayer: 'API 层',
        apiLayerDesc: '对外暴露的接口，提供简洁易用的 API',
        coreLayer: '核心层',
        coreLayerDesc: '业务逻辑处理，包括事务管理、查询引擎等',
        storageLayer: '存储层',
        storageLayerDesc: '文件系统操作，处理数据的持久化存储',
        utilityLayer: '工具层',
        utilityLayerDesc: '通用工具函数，包括加密、错误处理等',
        coreComponents: '核心组件',
        fileOperationManager: 'FileOperationManager',
        fileOperationManagerDesc: '文件操作管理，处理文件的读写、分块、合并等操作',
        transactionManager: 'TransactionManager',
        transactionManagerDesc: '事务管理，确保数据操作的原子性、一致性、隔离性和持久性',
        queryEngine: 'QueryEngine',
        queryEngineDesc: '查询引擎，处理复杂的查询条件和数据过滤',
        indexManager: 'IndexManager',
        indexManagerDesc: '索引管理，提高查询效率',
        metadataManager: 'MetadataManager',
        metadataManagerDesc: '元数据管理，存储表结构、索引等元数据信息',
        cacheManager: 'CacheManager',
        cacheManagerDesc: '缓存管理，提高数据访问速度',
        keyManager: 'KeyManager',
        keyManagerDesc: '密钥管理，处理数据加密和解密的密钥',
        storageAdapter: 'StorageAdapter',
        storageAdapterDesc: '存储适配器，提供统一的存储接口，支持不同的存储后端',
        dataFlow: '数据流向',
        dataFlowDesc: '从 API 调用到数据持久化的完整流程',
        performanceOptimization: '性能优化',
        optimization1: '分块存储',
        optimization1Desc: '单文件超过 5MB 自动分块，避免 RN FS 的限制',
        optimization2: '索引优化',
        optimization2Desc: '自动创建和维护索引，提高查询效率',
        optimization3: '缓存机制',
        optimization3Desc: '多级缓存设计，减少磁盘 I/O',
        optimization4: '批量操作',
        optimization4Desc: '支持批量写入和更新，减少磁盘操作次数',
        optimization5: '异步操作',
        optimization5Desc: '所有操作都是异步的，不阻塞主线程',
        securityFeatures: '安全特性',
        security1: '加密存储',
        security1Desc: '支持 AES-GCM 加密，密钥由用户完全控制',
        security2: '数据完整性',
        security2Desc: '使用校验和确保数据完整性',
        security3: '权限控制',
        security3Desc: '支持基本的权限控制，保护敏感数据',
        extensibility: '可扩展性',
        extensibilityDesc: '模块化设计，支持自定义存储适配器、加密算法等',
        customAdapter: '自定义适配器',
        customAdapterDesc: '可以实现自定义的存储适配器，支持不同的存储后端',
        customEncryption: '自定义加密',
        customEncryptionDesc: '可以实现自定义的加密算法，满足特定的安全需求',
        customQuery: '自定义查询',
        customQueryDesc: '可以扩展查询引擎，支持更复杂的查询条件',
        examplesTitle: '示例代码',
        examplesSubtitle: '各种使用场景的示例代码',
        transactionExample: '事务操作',
        transactionExampleDesc: '使用事务确保数据一致性',
        complexQueryExample: '复杂查询',
        complexQueryExampleDesc: '使用各种查询条件和操作符',
        encryptedStorageExample: '加密存储',
        encryptedStorageExampleDesc: '使用加密存储保护敏感数据',
        bulkOperationExample: '批量操作',
        bulkOperationExampleDesc: '使用批量操作提高性能',
        cacheExample: '缓存使用',
        cacheExampleDesc: '使用缓存提高数据访问速度',
        migrationExample: '数据迁移',
        migrationExampleDesc: '将数据从单文件迁移到分块存储',
        realWorldExample: '真实场景',
        realWorldExampleDesc: '在真实应用中的使用示例',
        userManagement: '用户管理',
        todoApp: '待办事项应用',
        settingsStorage: '设置存储',
        offlineData: '离线数据存储',
        changelogTitle: '更新日志',
        changelogSubtitle: 'expo-liteDBStore 的更新历史',
        version: '版本',
        date: '日期',
        changes: '变更内容',
        newFeatures: '新特性',
        bugFixes: 'bug 修复',
        improvements: '改进',
        breakingChanges: '破坏性变更',
        version100: '1.0.0',
        version100Date: '2025-11-29',
        version100Desc: '初始版本发布',
        version100Features: '完整的存储引擎功能，包括表操作、数据操作、事务管理、查询引擎等',
        version010: '0.1.0',
        version010Date: '2025-11-20',
        version010Desc: '测试版本发布',
        version010Features: '基本的存储功能，支持创建表、插入数据、查询数据等',
        version001: '0.0.1',
        version001Date: '2025-11-15',
        version001Desc: '第一个预发布版本',
        version001Features: '项目初始化，基本的文件存储功能',
        licenseTitle: '许可证',
        licenseSubtitle: 'MIT License',
        licenseDesc: 'expo-liteDBStore 采用 MIT 许可证开源',
        mitLicense: 'MIT 许可证',
        mitLicenseDesc: 'MIT 许可证是一种宽松的开源许可证，允许您自由使用、修改和分发软件，只要保留原始许可证和版权声明。'
    },
    en: {
        title: 'expo-liteDBStore',
        subtitle: 'Lightweight Local Storage Solution',
        description: 'Designed for React Native + Expo projects, no native dependencies required.',
        features: 'Core Features',
        feature1: 'Zero dependencies, zero configuration',
        feature2: 'Full TypeScript support',
        feature3: 'Support for encrypted storage',
        feature4: 'Support for transactions',
        feature5: 'Support for complex queries',
        feature6: 'Support for chunked storage',
        quickstart: 'Quick Start',
        installation: 'Installation',
        installationCmd: 'npm install expo-lite-db-store',
        usage: 'Basic Usage',
        api: 'API Documentation',
        architecture: 'Architecture',
        guides: 'Guides',
        examples: 'Examples',
        contribute: 'Contributing',
        changelog: 'Changelog',
        license: 'License',
        themeToggle: 'Toggle Theme',
        langToggle: 'Toggle Language',
        home: 'Home',
        gettingStarted: 'Getting Started',
        reference: 'API Reference',
        community: 'Community',
        search: 'Search...',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
        gettingStartedTitle: 'Getting Started with expo-liteDBStore',
        gettingStartedSubtitle: 'Quickly get started with the lightweight local storage solution designed for React Native + Expo projects.',
        prerequisites: 'Prerequisites',
        prereq1: 'React Native project',
        prereq2: 'Expo SDK 49+',
        prereq3: 'Node.js 16+',
        installationGuide: 'Installation Guide',
        installationSteps: 'Installation Steps',
        step1: 'Step 1: Install Dependencies',
        step2: 'Step 2: Configuration (Optional)',
        step3: 'Step 3: Start Using',
        configuration: 'Configuration',
        configurationFile: 'Configuration File',
        configurationExample: 'Configuration Example',
        basicUsage: 'Basic Usage',
        createTable: 'Create Table',
        insertData: 'Insert Data',
        queryData: 'Query Data',
        updateData: 'Update Data',
        deleteData: 'Delete Data',
        nextSteps: 'Next Steps',
        nextStep1: 'View API Reference',
        nextStep2: 'View Example Code',
        nextStep3: 'Learn About Architecture',
        nextStep4: 'Join Community Discussion',
        apiTitle: 'Complete API Documentation',
        apiSubtitle: 'Detailed information about all API methods and usage of expo-liteDBStore.',
        tableOperations: 'Table Operations',
        dataOperations: 'Data Operations',
        transactions: 'Transaction Management',
        cacheOperations: 'Cache Operations',
        utilityFunctions: 'Utility Functions',
        deleteTable: 'deleteTable',
        hasTable: 'hasTable',
        listTables: 'listTables',
        countTable: 'countTable',
        clearTable: 'clearTable',
        insert: 'insert',
        read: 'read',
        findOne: 'findOne',
        findMany: 'findMany',
        update: 'update',
        remove: 'remove',
        bulkWrite: 'bulkWrite',
        beginTransaction: 'beginTransaction',
        commit: 'commit',
        rollback: 'rollback',
        migrateToChunked: 'migrateToChunked',
        setCacheSize: 'setCacheSize',
        clearCache: 'clearCache',
        getCacheStats: 'getCacheStats',
        description: 'Description',
        parameters: 'Parameters',
        returns: 'Returns',
        example: 'Example',
        tableName: 'tableName',
        options: 'options',
        data: 'data',
        filter: 'filter',
        where: 'where',
        operations: 'operations',
        encrypted: 'encrypted',
        autoIndex: 'autoIndex',
        indexes: 'indexes',
        skip: 'skip',
        limit: 'limit',
        sort: 'sort',
        boolean: 'boolean',
        string: 'string',
        number: 'number',
        object: 'object',
        array: 'array',
        promise: 'Promise',
        void: 'void',
        writeResult: 'WriteResult',
        record: 'Record',
        null: 'null',
        true: 'true',
        false: 'false',
        usageExample: 'Usage Example',
        architectureTitle: 'Architecture Design',
        architectureSubtitle: 'Architecture design and core components of expo-liteDBStore',
        layeredArchitecture: 'Layered Architecture',
        apiLayer: 'API Layer',
        apiLayerDesc: 'External interfaces, providing simple and easy-to-use APIs',
        coreLayer: 'Core Layer',
        coreLayerDesc: 'Business logic processing, including transaction management, query engine, etc.',
        storageLayer: 'Storage Layer',
        storageLayerDesc: 'File system operations, handling data persistence',
        utilityLayer: 'Utility Layer',
        utilityLayerDesc: 'Common utility functions, including encryption, error handling, etc.',
        coreComponents: 'Core Components',
        fileOperationManager: 'FileOperationManager',
        fileOperationManagerDesc: 'File operation management, handling file read/write, chunking, merging, etc.',
        transactionManager: 'TransactionManager',
        transactionManagerDesc: 'Transaction management, ensuring atomicity, consistency, isolation, and durability',
        queryEngine: 'QueryEngine',
        queryEngineDesc: 'Query engine, handling complex query conditions and data filtering',
        indexManager: 'IndexManager',
        indexManagerDesc: 'Index management, improving query efficiency',
        metadataManager: 'MetadataManager',
        metadataManagerDesc: 'Metadata management, storing table structure, indexes, etc.',
        cacheManager: 'CacheManager',
        cacheManagerDesc: 'Cache management, improving data access speed',
        keyManager: 'KeyManager',
        keyManagerDesc: 'Key management, handling keys for data encryption and decryption',
        storageAdapter: 'StorageAdapter',
        storageAdapterDesc: 'Storage adapter, providing a unified storage interface for different storage backends',
        dataFlow: 'Data Flow',
        dataFlowDesc: 'Complete flow from API call to data persistence',
        performanceOptimization: 'Performance Optimization',
        optimization1: 'Chunked Storage',
        optimization1Desc: 'Automatic chunking for files larger than 5MB, avoiding RN FS limitations',
        optimization2: 'Index Optimization',
        optimization2Desc: 'Automatic creation and maintenance of indexes, improving query efficiency',
        optimization3: 'Cache Mechanism',
        optimization3Desc: 'Multi-level cache design, reducing disk I/O',
        optimization4: 'Batch Operations',
        optimization4Desc: 'Support for batch writes and updates, reducing disk operations',
        optimization5: 'Asynchronous Operations',
        optimization5Desc: 'All operations are asynchronous, not blocking the main thread',
        securityFeatures: 'Security Features',
        security1: 'Encrypted Storage',
        security1Desc: 'Support for AES-GCM encryption, keys fully controlled by users',
        security2: 'Data Integrity',
        security2Desc: 'Using checksums to ensure data integrity',
        security3: 'Permission Control',
        security3Desc: 'Support for basic permission control, protecting sensitive data',
        extensibility: 'Extensibility',
        extensibilityDesc: 'Modular design, supporting custom storage adapters, encryption algorithms, etc.',
        customAdapter: 'Custom Adapter',
        customAdapterDesc: 'Can implement custom storage adapters for different storage backends',
        customEncryption: 'Custom Encryption',
        customEncryptionDesc: 'Can implement custom encryption algorithms for specific security requirements',
        customQuery: 'Custom Query',
        customQueryDesc: 'Can extend the query engine to support more complex query conditions',
        examplesTitle: 'Example Code',
        examplesSubtitle: 'Example code for various usage scenarios',
        transactionExample: 'Transaction Operations',
        transactionExampleDesc: 'Use transactions to ensure data consistency',
        complexQueryExample: 'Complex Queries',
        complexQueryExampleDesc: 'Use various query conditions and operators',
        encryptedStorageExample: 'Encrypted Storage',
        encryptedStorageExampleDesc: 'Use encrypted storage to protect sensitive data',
        bulkOperationExample: 'Bulk Operations',
        bulkOperationExampleDesc: 'Use bulk operations to improve performance',
        cacheExample: 'Cache Usage',
        cacheExampleDesc: 'Use cache to improve data access speed',
        migrationExample: 'Data Migration',
        migrationExampleDesc: 'Migrate data from single file to chunked storage',
        realWorldExample: 'Real World Examples',
        realWorldExampleDesc: 'Usage examples in real applications',
        userManagement: 'User Management',
        todoApp: 'Todo App',
        settingsStorage: 'Settings Storage',
        offlineData: 'Offline Data Storage',
        changelogTitle: 'Changelog',
        changelogSubtitle: 'Update history of expo-liteDBStore',
        version: 'Version',
        date: 'Date',
        changes: 'Changes',
        newFeatures: 'New Features',
        bugFixes: 'Bug Fixes',
        improvements: 'Improvements',
        breakingChanges: 'Breaking Changes',
        version100: '1.0.0',
        version100Date: '2025-11-29',
        version100Desc: 'Initial release',
        version100Features: 'Complete storage engine functionality, including table operations, data operations, transaction management, query engine, etc.',
        version010: '0.1.0',
        version010Date: '2025-11-20',
        version010Desc: 'Beta release',
        version010Features: 'Basic storage functionality, support for creating tables, inserting data, querying data, etc.',
        version001: '0.0.1',
        version001Date: '2025-11-15',
        version001Desc: 'First pre-release version',
        version001Features: 'Project initialization, basic file storage functionality',
        licenseTitle: 'License',
        licenseSubtitle: 'MIT License',
        licenseDesc: 'expo-liteDBStore is open source under the MIT License',
        mitLicense: 'MIT License',
        mitLicenseDesc: 'The MIT License is a permissive open source license that allows you to freely use, modify, and distribute the software, as long as you retain the original license and copyright notice.'
    }
};

// 初始化内容
document.addEventListener('DOMContentLoaded', () => {
    updateContent();
});

// 添加平滑滚动效果
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
            target.scrollIntoView({
                behavior: 'smooth',
                block: 'start'
            });
        }
    });
});

// 添加页面加载动画
document.addEventListener('DOMContentLoaded', () => {
    document.body.classList.add('loaded');
});